version: '3.1'
services:
  hardware:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.hardware
    ports:
      - 50051:50051
    privileged: true
    command: ["python3", "-u", "server.py"]

  database:
    image: arm32v6/postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: rpi
      POSTGRES_DB: wakeus
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - HARDWARE_SERVICE_HOST=hardware:50051
      - PGHOST=database
      - PGDATABASE=wakeus
      - PGUSER=rpi
      - PGPASSWORD=password
    links:
      - database:database
      - hardware:hardware
    depends_on:
      - database
      - hardware
    ports:
      - 8000:8000
    expose:
      - 8000
    command: ["go", "run", "main.go"]

  client:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.client
    links:
      - api:api
      - hardware:hardware
    depends_on:
      - api
      - hardware
    ports:
      - 3000:3000
    expose:
      - 3000
    command: ["yarn", "start | cat"]

volumes:
  postgresql_data:
