FROM arm32v7/node:8-stretch-slim

ADD ./client/yarn.lock /yarn.lock
ADD ./client/package.json /package.json

ENV NODE_PATH=/node_modules
ENV PATH=$PATH:/node_modules/.bin
RUN yarn --network-timeout 600000

COPY . /wakeus
WORKDIR /wakeus/client
