FROM arm32v7/node:8-stretch-slim

ADD yarn.lock /yarn.lock
ADD package.json /package.json

ENV NODE_PATH=/node_modules
ENV PATH=$PATH:/node_modules/.bin
RUN yarn

COPY . /wakeus
WORKDIR /wakeus/client

CMD ["yarn start | cat"]
